version: "3.9"
services:
  bingoserver:
    container_name: bingo_container
    image: "bingo:c3.1-001"
    env_file:
      - ./docker-env-vars-for-bingo
    networks:
      - backend_space

  webserver:
    container_name: webserver_container
    image: "nginx:1.25.2"
    volumes:
      - /home/pablo/local-docker-volumes/nginx/para_bingo/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5000:80"
    networks: 
      - backend_space

networks:
  backend_space:
    name: backend_network
    driver: bridge