services:
  bingoserver:
    container_name: bingo_container
    image: "bingo:c3.1-001"
    env_file:
      - ./setup/docker-env-vars-for-bingo
    networks:
      - backend_space

  webserver:
    container_name: webserver_container
    image: "nginx:1.25.2"
    volumes:
      - ./setup/nginx.without.tls.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks: 
      - backend_space
      
  ingress:
    image: ngrok/ngrok:3-alpine
    command:
      - "http"
      - "http://host.docker.internal:80"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}

networks:
  backend_space:
    name: backend_network
    driver: bridge