version: "3.9"
services:
  bingoserver:
    container_name: bingo_container
    image: "bingo:c3.1-001"
    env_file:
      - ./docker-env-vars-for-bingo
    networks:
      - backend_space

  webserver:
    container_name: webserver_container
    image: "nginx:1.25.2"
    volumes:
      - /mnt/d/repos/bingo/setup/nginx.with.tls.conf:/etc/nginx/conf.d/default.conf
      - /home/pablo/local-docker-volumes/nginx/para_bingo/bingo-nginx-selfsigned.crt:/etc/ssl/certs/bingo-nginx-selfsigned.crt:ro
      - /home/pablo/local-docker-volumes/nginx/para_bingo/bingo-nginx-selfsigned.private.key:/etc/ssl/private/bingo-nginx-selfsigned.private.key:ro
    ports:
      - "5000:443"
    networks: 
      - backend_space

networks:
  backend_space:
    name: backend_network
    driver: bridge